name: Generate terraform docs
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read  # This is required for actions/checkout
  issues: write
  pull-requests: write
jobs:
  docs:
    runs-on: auto01
    defaults:
      run:
        shell: bash
        working-directory: /home/gal/terraform-fortimanager
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        output-file: terraform-docs.md
        output-method: inject
        git-push: "true"
