name: FMG01 Deploy

on:
    push:
        branches:
            - main

jobs: 
    deploy:
        runs-on: "self-hosted"
    
steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3