name: FMG01 Deploy
on:
    push:
        branches:
            - main
defaults: 
    run: 
        working-directory: /home/gal/terraform-fortimanager
jobs: 
    deploy:
        runs-on: "auto01"
        steps: 
            - name: Checkout
              uses: actions/checkout@v2

    terraform:
        name: terraform CI
        runs-on: "auto01"
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1  
            - name: terraform plan
              id: plan
              run: |
                terraform init && terraform plan -out=plan.out && terraform show -json plan.out > plan.out.json
            
            - name: terraform-compliance
              uses: terraform-compliance/github_action@main
              with:
                plan: plan.out.json
                features: ssh://git@github.com/terraform-compliance/user-friendly-features.git